### PR TITLE
Changed mansplain

### PR DESCRIPTION
**Pull request by francisbotero**
It comes across as unwelcoming language.

### CODE REVIEW

**Comment by aworkinglibrary** [comment]
The team discussed this and the term mansplain stands. While people of any gender can be guilty of patronizing behavior (and the code calls out that behavior generally), mansplaining refers to a particular kind of more prevalent behavior that specifically disrespects a woman's expertise. It is also something that many women on our team said they have routinely experienced in their careers, and the fact that the term has entered the popular lexicon is largely because it resonates so strongly with so many women.

Note that the code's express purpose is not only to foster a happy, welcoming team, but to "work against structural discrimination". Believing women's experiences is one step there. Actively working among ourselves to counter often ingrained norms that diminish women's abilities to succeed is another.

**Comment by justinglow** [comment]
:+1:

**Comment by melissabell** [comment]
:+1:

**Comment by jasonsantamaria** [comment]
:+1:

**Comment by tangentialism** [comment]
Stet. :+1:

**Comment by wnstn** [comment]
👍

**Comment by sixfoot6** [comment]
:+1:

**Comment by eelzon** [comment]
:raised_hands:

**Comment by gesteves** [comment]
:+1:

**Comment by ashleytwaddell** [comment]
:+1:

**Comment by kissane** [comment]
+1

**Comment by kissane** [comment]
:+1:

**Comment by beep** [comment]
👍

**Pull request closed without merging**
