### PR TITLE
Add tone policing to Unacceptable behaviors

### PR DESCRIPTION
**Pull request by eelzon**
This PR adds the following to the CoC section on Unacceptable behaviors:

`The same goes for [tone policing](http://tooyoungforthelivingdead.tumblr.com/tone-policing), or responding negatively to the emotion behind a person’s message while ignoring its content (telling someone who is discussing an issue that makes them upset to “calm down” instead of responding to their concerns is an example of tone policing).`

### CODE REVIEW

**Comment by eelzon** [comment]
Closing to reopen from `master`

**Comment by eelzon** [comment]
Reopening, sorry!

**Comment by cwilliams2k4** [comment]
What would be the best strategy for addressing an inappropriate tone with a coworker during a conversation? Would you wait until the issue itself has been addressed to bring it up? I know the first step to any conflict resolution is to attempt to come to an understanding between two people prior to engaging HR or their manager in general, so wondering how to best handle that.

**Comment by aworkinglibrary** [comment]
@cwilliams2k4 The section on [reporting a problem](http://code-of-conduct.voxmedia.com/#Reporting%20a%20problem) covers that, I believe?

**Comment by sixfoot6** [comment]
:+1:

**Comment by melissabell** [comment]
:+1:

**Pull request merged**
